### ISSUE TITLE
Unable to enable flymake backends

### ISSUE THREAD

**Issue by fast-90** [com4/flymake-mypy#2]
Hi! I came across your repo through an old reddit post as I was looking to get mypy and flymake working without LSP.

Unfortunately the package does not seem to be working for me, as I don't see any flymake lines in my Python script buffer (which has an obvious mypy error). This is my config (I use elpaca and tree-sitter):

```elisp
(use-package flymake-mypy
  :elpaca (flymake-mypy
             :type git
             :host github
             :repo "com4/flymake-mypy"))

(defun my/flymake-eglot-fix ()
    "Add flymake checkers after Eglot replaces the checkers."
    (when (derived-mode-p 'python-ts-mode)
      ;; re-enable the default python.el checker
      (add-hook 'flymake-diagnostic-functions 'python-flymake nil t)
      (flymake-mypy-enable)))

(add-hook 'eglot-managed-mode-hook 'my/flymake-eglot-fix)
```

Things I tried in addition:

- I have also set `flymake-mypy-executable` to ensure my venv's mypy is used. 
- Use it without eglot, i.e. disable eglot and try to run `flymake-mypy-enable`. Again nothing happens. 

What is weird is that although I can see both `python-flymake` and `flymake-mypy--run` in `flymake-diagnostic-functions`, both stay disabled for me no matter what I do (i.e. the backends show in `flymake-disabled-backends`, and `flymake-running-backends` is empty).

Would you have any idea what I am doing wrong here? Is it still working properly for you?

**Comment by com4** [comment]
Thanks for the report! I hadn't noticed it wasn't running for me either.

It looks like something changed with one of the project.el variables
that are used. I've pushed a fix under the 0.3.1 tag if you want to see
if that works better.
